[package]
name = "bevy-midi-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.16.0" }
ron = "0.8.1"
midi-graph = { git = "https://github.com/grimace87/midi-graph.git", rev = "84a7df8e88d6ecbb4c9822e32aadca0db9d351f2" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
avian3d = "0.3.0"
