[package]
name = "bevy-midi-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.3", features = ["jpeg"] }
ron = "0.8.1"
midi-graph = { git = "https://github.com/grimace87/midi-graph.git", rev = "2b90c0a8e10e7d14a79fb7c3742b45f78637b0fe" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
avian3d = "0.2.0"
