[package]
name = "bevy-midi-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.16.0" }
ron = "0.8.1"
midi-graph = { git = "https://github.com/grimace87/midi-graph.git", rev = "7335e70fd34a3a8a1c3b83f76dfae899c18583f6" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
avian3d = "0.2.0"
