[package]
name = "bevy-midi-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.0", features = ["jpeg"] }
ron = "0.8.1"
midi-graph = { git = "https://github.com/grimace87/midi-graph.git", rev = "47646dae90255d7000f108a05195f2ad510b1e6a" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
avian3d = "0.2.0"
